## Advance Operation with Business Examples

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Data structure: [restaurant_id,2021,2022,2023,2024]
sales_data=np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,270000],
    [4,180000,210000,240000,270000],
    [5,160000,185000,205000,230000]
])

#### Slicing

In [6]:
print(f"Sliced rows data\n{sales_data[0:3]}")
print(f"Sliced columns data\n{sales_data[:,1:]}")

Sliced rows data
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 270000]]
Sliced columns data
[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 270000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


### Suming data

In [9]:
print(f"Vertical addition\n{np.sum(sales_data[:, 1:], axis=0)}")
print(f"Horizontal addition\n{np.sum(sales_data[:, 1:], axis=1)}")

Vertical addition
[ 810000  945000 1085000 1210000]
Horizontal addition
[800000 610000 960000 900000 780000]
